name: Android CI

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/upload-artifact@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

  build:
    name: Build APK
    needs: [ test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/upload-artifact@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

  deploy:
    name: Deploy on branch develop
    if: github.ref == 'refs/heads/develop'
    needs: [ build ]
    runs-on: ubuntu-latest
    container: alvrme/alpine-android:android-33-jdk11

    steps:
      - uses: actions/checkout@v3

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build develop APK
        run: ./gradlew assembleDevelopDebug

      - name: Upload to Firebase (Fastlane)
        run: |
          extras fastlane
          fastlane android distribute_firebase
